export const INTEGER = {
  APP_BAR_MOBILE: 56,
  APP_BAR_DESKTOP: 64,
  DRAWER_WIDTH: 290,

  //USER ROLES
  ADMIN_ROLE: 2412,
  EMPLOYEE_ROLE: 1108,
  CUSTOMER_ROLE: 1998,

  //ROOM STATUS
  ROOM_EMPTY: 1,
  ROOM_PENDING: 2,
  ROOM_RENTED: 3,

  //BOOKING STATUS
  BOOKING_CANCELED: 1, // user cancelled booking before check-in
  BOOKING_IN_PROGRESS: 2, // user paid but not check in yet
  BOOKING_CHECK_IN: 3, // user checked in
  BOOKING_CHECK_OUT: 4, // user check-out

  //REVIEW STATUS
  REVIEW_WAITING: 1,
  REVIEW_ACCEPTED: 2,
  REVIEW_REJECTED: 3,

  // DISCOUNT TYPE
  AMOUNT_DISCOUNT: 0,
  PERCENTAGE_DISCOUNT: 1,
};

export const STRING = {
  // User action types
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP",
  LOG_OUT: "LOG_OUT",
  GET_INFO: "GET_INFO",

  // Hotel action types
  CREATE_HOTEL: "CREATE_HOTEL",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  DELETE_HOTEL: "DELETE_HOTEL",
  GET_ALL_HOTEL: "GET_ALL_HOTEL",

  // Room action types
  CREATE_ROOM: "CREATE_ROOM",
  UPDATE_ROOM: "UPDATE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  GET_ALL_ROOM: "GET_ALL_ROOM",

  // Room Service action types
  CREATE_ROOM_SERVICE: "CREATE_ROOM_SERVICE",
  UPDATE_ROOM_SERVICE: "UPDATE_ROOM_SERVICE",
  DELETE_ROOM_SERVICE: "DELETE_ROOM_SERVICE",
  GET_ALL_ROOM_SERVICE: "GET_ALL_ROOM_SERVICE",

  // Room type action types
  CREATE_ROOM_TYPE: "CREATE_ROOM_TYPE",
  UPDATE_ROOM_TYPE: "UPDATE_ROOM_TYPE",
  DELETE_ROOM_TYPE: "DELETE_ROOM_TYPE",
  GET_ALL_ROOM_TYPE: "GET_ALL_ROOM_TYPE",

  // Booking action types
  CREATE_BOOKING: "CREATE_BOOKING",
  UPDATE_BOOKING: "UPDATE_BOOKING",
  CHECK_IN_BOOKING: "CHECK_IN_BOOKING",
  CHECK_OUT_BOOKING: "CHECK_IN_BOOKING",
  DELETE_BOOKING: "DELETE_BOOKING",
  GET_ALL_BOOKING: "GET_ALL_BOOKING",
  CANCEL_BOOKING: "CANCEL_BOOKING",

  // Booking action types
  CREATE_BACKUP: "CREATE_BACKUP",
  DELETE_BACKUP: "DELETE_BACKUP",
  GET_ALL_BACKUP: "GET_ALL_BACKUP",
  UPDATE_BACKUP: "UPDATE_BACKUP",
  RESTORE: "RESTORE",

  // Expense action types
  CREATE_EXPENSE: "CREATE_EXPENSE",
  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  GET_ALL_EXPENSE: "GET_ALL_EXPENSE",

  // Account action types
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  GET_ALL_ACCOUNT: "GET_ALL_ACCOUNT",

  // Log action types
  GET_ALL_LOG: "GET_ALL_LOG",

  // Review action types
  UPDATE_REVIEW: "UPDATE_REVIEW",
  GET_ALL_REVIEW: "GET_ALL_REVIEW",

  // Account action types
  CREATE_DISCOUNT: "CREATE_DISCOUNT",
  UPDATE_DISCOUNT: "UPDATE_DISCOUNT",
  DELETE_DISCOUNT: "DELETE_DISCOUNT",
  GET_ALL_DISCOUNT: "GET_ALL_DISCOUNT",

  // Combo action types
  CREATE_COMBO: "CREATE_COMBO",
  UPDATE_COMBO: "UPDATE_COMBO",
  DELETE_COMBO: "DELETE_COMBO",
  GET_ALL_COMBO: "GET_ALL_COMBO",

  // Peak Day action types
  CREATE_PEAK_DAY: "CREATE_PEAK_DAY",
  UPDATE_PEAK_DAY: "UPDATE_PEAK_DAY",
  DELETE_PEAK_DAY: "DELETE_PEAK_DAY",
  GET_ALL_PEAK_DAY: "GET_ALL_PEAK_DAY",

  // SYSTEM
  LOCAL_STORAGE_PROFILE_KEY:
    "065211f7a119d769f567ae067eb75951714d6a1df57bc30ff695befaed27059a613c76bdebf98e6d9700d4db50a99f7c",

  // SERVER URL
  SERVER_URL: "http://localhost:5000",
};
