// fake is city_number in db
export const city = [
  { name: "", fake: 0 }, //default value
  { name: "An Giang", fake: 1 },
  { name: "Bà Rịa – Vũng Tàu", fake: 2 },
  { name: "Bạc Liêu", fake: 3 },
  { name: "Bắc Giang", fake: 4 },
  { name: "Bắc Kạn", fake: 5 },
  { name: "Bắc Ninh", fake: 6 },
  { name: "Bến Tre", fake: 7 },
  { name: "Bình Dương", fake: 8 },
  { name: "Bình Định", fake: 9 },
  { name: "Bình Phước", fake: 10 },
  { name: "Bình Thuận", fake: 11 },
  { name: "Cà Mau", fake: 12 },
  { name: "Cao Bằng", fake: 13 },
  { name: "Cần Thơ", fake: 14 },
  { name: "Đà Nẵng", fake: 15 },
  { name: "Đắk Lắk", fake: 16 },
  { name: "Đắk Nông", fake: 17 },
  { name: "Điện Biên", fake: 18 },
  { name: "Đồng Nai", fake: 19 },
  { name: "Đồng Tháp", fake: 20 },
  { name: "Gia Lai", fake: 21 },
  { name: "Hà Giang", fake: 22 },
  { name: "Hà Nam", fake: 23 },
  { name: "Hà Nội", fake: 24 },
  { name: "Hà Tĩnh", fake: 25 },
  { name: "Hải Dương", fake: 26 },
  { name: "Hải Phòng", fake: 27 },
  { name: "Hậu Giang", fake: 28 },
  { name: "Hòa Bình", fake: 29 },
  { name: "Hồ Chí Minh", fake: 30 },
  { name: "Hưng Yên", fake: 31 },
  { name: "Khánh Hòa", fake: 32 },
  { name: "Kiên Giang", fake: 33 },
  { name: "Kon Tum", fake: 34 },
  { name: "Lai Châu", fake: 35 },
  { name: "Lạng Sơn", fake: 36 },
  { name: "Lào Cai", fake: 37 },
  { name: "Lâm Đồng", fake: 38 },
  { name: "Long An", fake: 39 },
  { name: "Nam Định", fake: 40 },
  { name: "Nghệ An", fake: 41 },
  { name: "Ninh Bình", fake: 42 },
  { name: "Ninh Thuận", fake: 43 },
  { name: "Phú Thọ", fake: 44 },
  { name: "Phú Yên", fake: 45 },
  { name: "Quảng Bình", fake: 46 },
  { name: "Quảng Nam", fake: 47 },
  { name: "Quảng Ngãi", fake: 48 },
  { name: "Quảng Ninh", fake: 49 },
  { name: "Quảng Trị", fake: 50 },
  { name: "Sóc Trăng", fake: 51 },
  { name: "Sơn La", fake: 52 },
  { name: "Tây Ninh", fake: 53 },
  { name: "Thái Bình", fake: 54 },
  { name: "Thái Nguyên", fake: 55 },
  { name: "Thanh Hóa", fake: 56 },
  { name: "Thừa Thiên - Huế", fake: 57 },
  { name: "Tiền Giang", fake: 58 },
  { name: "Trà Vinh", fake: 59 },
  { name: "Tuyên Quang", fake: 60 },
  { name: "Vĩnh Long", fake: 61 },
  { name: "Vĩnh Phúc", fake: 62 },
  { name: "Yên Bái", fake: 63 },
];

export const HOTEL_SERVICES = [
  { name: "Wi-Fi miễn phí trong tất cả các phòng!", icon: "bx:wifi", id: 0 },
  { name: "Dọn phòng hằng ngày", icon: "carbon:clean", id: 1 },
  { name: "Đưa đón sân bay", icon: "bxs:taxi", id: 2 },
  { name: "Quán bar", icon: "emojione-monotone:tropical-drink", id: 3 },
  { name: "Gym", icon: "iconoir:gym", id: 4 },
  { name: "Hồ bơi 4 mùa", icon: "icon-park-outline:swimming-pool", id: 5 },
  { name: "Sân golf", icon: "ic:baseline-golf-course", id: 6 },
  { name: "Bãi đỗ xe", icon: "uil:parking-circle", id: 7 },
];
