export const INTEGER = {
  APP_BAR_MOBILE: 56,
  APP_BAR_DESKTOP: 64,
  DRAWER_WIDTH: 260,

  //BOOKING STATUS
  BOOKING_CANCELED: 1, // user cancelled booking before check-in
  BOOKING_IN_PROGRESS: 2, // user paid but not check in yet
  BOOKING_CHECK_IN: 3, // user checked in
  BOOKING_CHECK_OUT: 4, // user check-out

  // DISCOUNT TYPE
  AMOUNT_DISCOUNT: 0,
  PERCENTAGE_DISCOUNT: 1,
};

export const STRING = {
  // User action types
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP",
  LOG_OUT: "LOG_OUT",
  GET_INFO: "GET_INFO",

  // Hotel
  GET_ALL_HOTEL: "GET_ALL_HOTEL",

  // Room type
  GET_AVAILABLE_ROOM_TYPE: "GET_AVAILABLE_ROOM_TYPE",

  // Booking
  GET_ALL_BOOKING_BY_USER: "GET_ALL_BOOKING_BY_USER",
  CANCEL_BOOKING: "CANCEL_BOOKING",
  UPDATE_BOOKING: "UPDATE_BOOKING",

  // review
  GET_ALL_REVIEW_BY_USER: "GET_ALL_REVIEW_BY_USER",

  // LOCAL STORAGE
  LOCAL_STORAGE_PROFILE_KEY:
    "9185c1ee5c530a3957a501799c35a4d1da23f004f81eb5621537a0d621571b4b7d3949c365296ff34e1167f2c2e8d35c97522b4214ce0984fb3b67793b1f020f",

  LOCAL_STORAGE_BOOKING_INFO: "BOOKING_INFO",

  // SERVER URL
  SERVER_URL: "http://localhost:5000",
};
